######################################################################
# Automatically generated by qmake (2.01a) ??? ??? 21 12:30:33 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . src
INCLUDEPATH += . src

# Input
HEADERS += src/window.h
SOURCES += src/main.cpp src/window.cpp
